# -*- coding: utf-8 -*-
"""Python Exercise 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMj6BCXsCMw_v11qHw0Z87e3OB7KEHQj
"""

#Exercise for this Class

'''
1. Why would we need multiple data types to be stored in same list? Try to think of a real world example
 and use it in any way you want.()'''


 '''
2. Try out a sorting algorithm in Python(any). Below is the code for buble sort in Cpp
// C++ Program to how to sort an array

#include <algorithm>
#include <iostream>
using namespace std;

int main()
{
    // Initializing an array
    int arr[] = { 5, 4, 1, 2, 3 };

    // Calculate the size of the array
    int n = sizeof(arr) / sizeof(arr[0]);

    // Print the array before sorting the elements
    cout << "Array Before Sorting: ";
    for (int i = 0; i < n; i++) {
        cout << arr[i] << " ";
    }
    cout << endl;

    // Sort the array
    sort(arr, arr + n);

    // Print the array after sorting the elements
    cout << "Array After Sorting: ";
    for (int i = 0; i < n; i++) {
        cout << arr[i] << " ";
    }

    return 0;
}

3. Task 1

a. Write a small python program with some basic calculation functions like add, subtract,
divide, min, max etc. All these must be in form of separate functions since these will be used later.
You can also print the answer in any format that you want.

b. Write another python program to import the file in point1 and use the above functions on user
input data to get results. Eg file1.add(1,4) must return 5 in file2.


Bonus: Try to explore how a function can take variable number of arguments instead of a
fixed number of arguments. Eg. file1.max(1,4) is 4, here we are taking only two arguments i.e 1 and 4.
But we may need to find the max between more than two numbers like max(1,3,4,7) is 7.
You may need explore the syntax in python to accommodate this requirement in functions documentation.

4.
(a)Append all the keys into one single string with "::" between the keys(Call this string st). -
"key1::key2::key3"

(b)Sum up all the values of all the keys and print this number(sum). - 9
(c)Add a new key:value pair to the dictionary with key as string st and value as output of (b) sum.

Hint:
1.Loop over the keys of the dictionary
2. String concatenation(string3 = string1 + string2)

'''

# question 1
name=input("enter name:")
age=int(input("enter age:"))
state=input("enter state:")
bsc_course=input("true/false")
dict={"name":name, "age":age,"state":state,"configured":bsc_course}

print(dict)

#question 3 a,b
def addition(a,b):
  return(a+b)
def substraction(a,b):
  return a-b
a=int(input("enter value a:"))
b=int(input("enter value b:"))

print("addition:", addition(a,b))
print("substraction",substraction(a,b))

# divistion
x=int(input("enter val:x"))
y=int(input("enter val:y"))
division=x/y
print(division)

s=int(input("enter1:"))
t=int(input("enter 2:"))
if s>t:
  print("max",s)
print("min",t)

# 4 doubt
def concatenate_keys(dictionary):
  keys_list = list(dictionary.keys())
  st = "::".join(keys_list)
  return st

# Example usage:
my_dict = {"key1": "value1", "key2": "value2", "key3": "value3"}
result = concatenate_keys(my_dict)
print(result)  # Output: "key1::key2::key3"

#sample
keys = ['key1', 'key2', 'key3']
st = "::".join(keys)
print(st)

#trash
def get_keys_from_user():
  """Prompts the user to enter keys for a dictionary and returns a list of keys."""

  num_keys = int(input("Enter the number of keys: "))
  keys = []

  for i in range(num_keys):
    key = input(f"Enter key {i+1}: ")
    keys.append(key)

  return keys

# Example usage:
keys = get_keys_from_user()
print(keys)

# question 4 (b)
my_dict = {"a": 1, "b": 2, "c": 3}
total_sum = sum(my_dict.values())

print("Sum of all values:", total_sum)
# 4(c)Add a new key:value pair to the dictionary with key as string st and value as output of (b) sum.

# Add a new key-value pair
my_dict["d"] = 52
print(my_dict)

#Question
#Name to roll number dictionary
d = {"abhin":23, "nirmal":34, "nivedita": 54, "thomas":40, "ojha":21}
"""
# using dictionary keys and values perform below tasks.
1. print the rollnumber of ojha.
2. find the name of the person with roll number 34.
3. print the number of roll numbers between thomas and nirmal.
4. print all keys and values of this dictionary in this format.
"My name is <> and my roll number is <>" - for all persons
"""

# question d 1
 d = {"abhin":23, "nirmal":34, "nivedita": 54, "thomas":60, "ojha":21}
#q1
roll_number_ojha = d["ojha"]

#q2
for name, roll in d.items():
    if roll == 34:
        person_34 = name
        break
#q3
# Get the roll numbers for thomas and nirmal
thomas_roll = d["thomas"]
print(thomas_roll)
nirmal_roll = d["nirmal"]
print(nirmal_roll)
# Find the number of roll numbers between thomas and nirmal
count = 0
for roll in d.values():
    if thomas_roll <= roll <= nirmal_roll:
      count += 1
#q4
for name,roll in d.items():
  print("my name is",name,"and my roll number is",roll) #q4


print("Number of roll numbers between thomas and nirmal:", count)
print("34 roll number :", person_34) # q1
print("Roll number of ojha:", roll_number_ojha)#q2
print("the number of roll numbers between thomas and nirmal",count)#q3

'''
1
(a)Append all the keys into one single string with "::" between the keys(Call this string st). -
"key1::key2::key3"

(b)Sum up all the values of all the keys and print this number(sum). - 9
(c)Add a new key:value pair to the dictionary with key as string st and value as output of (b) sum.

Hint:
1.Loop over the keys of the dictionary
2. String concatenation(string3 = string1 + string2)

'''

#Questions
#1. Print all the odd numbers divisible by 5 from 1 to 100.
#2. Take input n from user and print first n prime numbers.
#3. Print the following pattern(use a for loop)
'''
1
22
333
4444
55555
'''

# q1
n=5
for i in range(1,100):
  if i%5==0:
    print(i,end=" ")

#q2
def is_prime(num):

  if num <= 1:
    return False
  if num <= 3:
    return True
  if num % 2 == 0 or num % 3 == 0:
    return False
  i = 5
  while i * i <= num:
    if num % i == 0 or num % (i + 2) == 0:
      return False
    i += 6
  return True

def print_first_n_primes(n):
  """Prints the first n prime numbers."""
  count = 0
  num = 2
  while count < n:
    if is_prime(num):
      print(num, end=" ")
      count += 1
    num += 1

# Get the number of primes from the user
n = int(input("Enter the number of prime numbers to print: "))

print_first_n_primes(n)

#q 3
for i in range(1,6):
  for j in range(i):
    print(i,end="")
  print()

#Question
li - [1,2,3,5,5,4,3,4,3,3,5,3,2,12,5,5,4,32,23,5,4,34,324,23,2]
# print the sum of elements from index 3 to 14(use list indexing)
# print sum of all odd indexes
# print the sum of the differences between any two consecutive indexes.[1,5,2] 5-1 + 2-5 = 1, print(1)

#q1
li =[1,2,3,5,5,4,3,4,3,3,5,3,2,12,5,5,4,32,23,5,4,34,324,23,2]
s=0
for i in range(3,15):
  s=s+li[i]
print(" q1 :the sum of elements from the given index is ",s)
#q2
sum=0
for i in range(1,len(li),2):
  sum=sum+li[i]
print("q2 the sum of the list range",sum)
#Q3
i=0
s=0
# Iterate up to the second-to-last element to avoid going out of bounds
for i in range (0,len(li) - 1):
  s=li[i+1]-li[i]
print(" Iterate up to the second-to-last element to avoid going out of bounds",s)