# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piQVZTMgc4RW42riuUXSDmKgfBP5fJ7R
"""

#1. merge these two dictionaries. 2+ ways
dict1 = {'a': 10, 'b': 8}
dict2 = {'d': 6, 'c': 4}
#dict1.update(dict2)
for i in dict2:
    dict1[i]=dict2[i]

print(dict1)

#2. find all duplicate characters in a string.
st = "abccddeertyuui"
dup=[]
for i in st:
    if st.count(i)>1:
        if i not in dup:
            dup.append(i)
print(dup)

gmax=(1,2,432,14,321,321,2)
def Max(x):
  m=x[0]
  for i in x:
    if i>m:
      m=i
    return m
print(max(gmax))