# -*- coding: utf-8 -*-
"""assignment_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvS0VNmBClotMF0zUvH3BYBBAxStuIVe
"""

'''
In this task you are to write a mini python library(a python file with defined functions like the
calculator you wrote in the previous class)

You are a Hockey coach of an olympic team. There are 10 players in your team. You need a mini-library that
will help you manage ypur team better.

1. Define a dictionary(in ipynb notebook) of your team. The key must be a name and the value must be another dictionary
with four field(keys):-
    height - in metres
    position(Left Back/Right Back/Middle Back/Goalkeeper/Front Left/Front Right/Front Center, Middle Center, Middle Right, Middle Left)
    physique - (explosive, stamina, all-round)
    nature - (realist/idealist)
    age - in years

Example of two players dictionary is below(you must draft a team of your choice with 10 players)
{"sai":{"heigth":1.6, "position":"Front Left", "physique": "explosive", "nature":"idealist", "age":25}
, "aditya":{"heigth":1.5, "position":"Front Center", "physique": "all-round", "nature":"realist", "age":23}}

2. Write a separate python file "hockeyTeamManager.py". In this you must write the following functions:-
(a) Get the average height and age of a team.
(b) Get number of explosive/stamina/all-rounders you a team.(print in any format you desire)
(c) Find the position that two players play(if any)
(d) Find the position that no player plays(if any)
(e) Find the nature of the team. Based on number of realists and idealist if 70% of the team is of one side then conclude for that side
    Example
        if 7/10 are idealists then team is idealist.(same for realist)
        if 6/10 or 5/10 are idealist or realists then team is a "mix"
(f) Find the overall physique of the team. The physique that occurs most number of times is the physique of the team
(g) If a new player is to be added into the team then find the maximum age allowed so that the average age of the team
    does not exceed 24 years.
(h) Write a print function to print in a clear way all the players with their respective positions in case coach wants to
    review the lineup.(example:  <Name> Plays in position <position>" )
(i) Write a function to find all those athletes who are of a particular physique(take physique as argument to function)
(j) Write a function to find all those athletes who are of a particular nature(take nature as argument to function)
    Example for above two(i,j)
        >hockeyTeamManager.GetPlayersWithPhysique(playerDictionary, physiqueToFilter)
        Should print name of players with physique are given in argument(explosive/stamina/all-round)

3. Now import this python file into the notebook and use all these functions one after the other.
Note: these functions must not be seen anywhere in the notebook. They should be written in the python file which you import into
the notebook.

'''

#question 1
team={
"rajesh":{"heigth":5.9, "position":"Front Left", "physique": "explosive", "nature":"idealist", "age":25},
"pavan":{"heigth":5.4, "position":"left back", "physique": "all-round", "nature":"realist", "age":23},
"vardhan":{"heigth":5.2, "position":"right back", "physique": "explosive", "nature":"idealist", "age":25},
"kumar":{"heigth":1.5, "position":"right front", "physique": "all-round", "nature":"realist", "age":23},
"siva":{"heigth":4.9, "position":"goal keeper", "physique": "explosive", "nature":"idealist", "age":25},
"vijay":{"heigth":4.5, "position":"Front Center", "physique": "all-round", "nature":"realist", "age":23},
"surya":{"heigth":5.5, "position":"Front Left", "physique": "explosive", "nature":"idealist", "age":25},
"praveen":{"heigth":6.0, "position":"Front Center", "physique": "all-round", "nature":"realist", "age":23},
"nandhu":{"heigth":5.6, "position":"Front Left", "physique": "explosive", "nature":"idealist", "age":25},
"ganesh":{"heigth":5.5, "position":"Front Center", "physique": "all-round", "nature":"idealist", "age":23}
}

#question 2(a.1)
#Get the average height of a team.
def avg_height(a):
  he=0
  length=len(a)
  for name,i in a.items():
    he=he+i['heigth']
  avhe=he/length
  return(avhe)
print(avg_height(team))

#question 2(a.2)
#Get the average height of a team.
def avg_age(a):
  ag=0
  length=len(a)
  for name,i in a.items():
    ag=ag+i['age']
  avag=ag/length
  return(avag)
print(avg_age(team))

#question 2(b)
# Get number of explosive/stamina/all-rounders you a team.(print in any format you desire)

def phy_count(a):
  exp=0
  sta=0
  all=0
  for name,i in a.items():
    if i['physique']=="explosive":
      exp=exp+1
    elif i['physique']=='stamina':
      sta+=1
    else:
      all+=1
    return(exp,sta,all)
print(phy_count(team))
print("explosive=",phy_count(team)[0])
print("stamina=",phy_count(team)[1])
print("all-round=",phy_count(team)[2])

#question 2(c)
#Find the position that two players play(if any)
pos=[]
for name,i in team.items():
  pos.append(i['position'])
print(pos)

#question 2(d)
#Find the position that no player plays(if any
for i in pos:
  if pos.count(i)==1:
    print(i)
    break
  else:
    print("no player plays")

#question 2(e)
#Find the nature of the team. Based on number of realists and idealist if 70% of the team is of one side then conclude for that side
'''  Example
    if 7/10 are idealists then team is idealist.(same for realist)
    if 6/10 or 5/10 are idealist or realists then team is a "mix"   '''
def nature(a):
  real=0
  ide=0
  for name,i in a.items():
    if i['nature']=="realist":
      real=real+1
    else:
      ide=ide+1
  return(real,ide)


real, ide = nature(team)
print(nature(team))
if real>ide:
  print("realist")
elif real<ide:
  print("idealist")
else:
  print("mix")

#question 2(f)
# Find the overall physique of the team. The physique that occurs most number of times is the physique of the team

def overall_physique(a):
  exp=0
  sta=0
  all=0
  for name,i in a.items():
    if i['physique']=="explosive":
      exp=exp+1
    elif i['physique']=='stamina':
      sta+=1
    else:
      all+=1
  if exp>sta and exp>all:
    return("explosive")
  elif sta>exp and sta>all:
    return("stamina")
  else:
    return("all-round")
print("overall physique of the team is:",overall_physique(team))

#question 2(g)
#If a new player is to be added into the team then find the maximum age allowed so that the

def max_age(a):
  ag=0
  length=len(a)
  for name,i in a.items():
    ag=ag+i['age']
  avag=ag/length
  max_allowed_age = (24 * (length + 1)) - avag
  max_allowed_age = (24 * (length + 1)) - ag
  return max_allowed_age

print(max_age(team))

#question 2(h)
# Write a print function to print in a clear way all the players with their respective positions in case coach wants to
#   review the lineup.(example:  <Name> Plays in position <position>" )

def print_players(a):
  for name,i in a.items():
    print(name,"plays in position",i['position'])
print_players(team)

#question 2(i)
#Write a function to find all those athletes who are of a particular physique(take physique as argument to function)
def find_physique(a,physique):
  for name,i in a.items():
    if i['physique']==physique:
      print(name)
find_physique(team,"explosive")

#question 2(j)
'''
 Write a function to find all those athletes who are of a particular nature(take nature as argument to function)
    Example for above two(i,j)
        >hockeyTeamManager.GetPlayersWithPhysique(playerDictionary, physiqueToFilter)
        Should print name of players with physique are given in argument(explosive/stamina/all-round)
'''
def find_nature(a,nature):
  for name,i in a.items():
    if i['nature']==nature:
      print(name)
find_nature(team,"idealist")