# -*- coding: utf-8 -*-
"""NB Numerical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrMy9LIW008VuAwWxrmuJOREy6Ugi4Mx
"""

from sklearn.naive_bayes import GaussianNB
import numpy as np

# Small dataset: [study_hours, sleep_hours]
X = np.array([
    [2, 8],   # low study, high sleep -> Fail
    [3, 7],   # low study, moderate sleep -> Fail
    [4, 6],   # medium study, medium sleep -> Pass
    [5, 5],   # good study, less sleep -> Pass
    [6, 6],   # high study, medium sleep -> Pass
    [1, 9]    # very low study, high sleep -> Fail
])

# Labels: 0 = Fail, 1 = Pass
y = np.array([0, 0, 1, 1, 1, 0])

# Create and train Naive Bayes model
model = GaussianNB()
model.fit(X, y)

# Predict for a new student
new_student = np.array([[4, 7]])   # 4 hours study, 7 hours sleep
prediction = model.predict(new_student)

print("Prediction for new student:", "Pass" if prediction[0] == 1 else "Fail")